name: Wakatime Profile Stats
description: "A GitHub Action to update your GitHub profile README with certain stats from Wakatime"
author: ZerGo0
branding:
  icon: "activity"
  color: "red"
inputs:
  GH_TOKEN:
    description: "GitHub access token with Repo scope"
    required: true
    default: ${{ github.token }}

  WAKATIME_API_KEY:
    description: "Your Wakatime API Key"
    required: true
runs:
  using: docker
  image: Dockerfile
